language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - swig
      - libusb-1.0-0-dev
cache:
  - pip
  - apt
install:
  # Update pip and setuptools to the latest version.
  - pip install -U pip setuptools
script: python setup.py test
